name: Zip and Upload to S3

on:
  push:
    branches:
      - main  # Trigger this action on push to main branch

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Zip directories and upload to S3
      run: |
        for dir in $(find . -type d); do
          if [ "$dir" != "./.github" ]; then  # Ignore .github directory
            zip -r "${dir}.zip" "$dir"
            aws s3 cp "${dir}.zip" s3://lambda-foodieflow/
          fi
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
