name: Zip and Upload to S3

on:
  push:
    branches:
      - main  # Trigger this action on push to main branch

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install --upgrade --user awscli

    - name: Zip directories and upload to S3
      run: |
        for dir in $(find $GITHUB_WORKSPACE -type d -not -path "$GITHUB_WORKSPACE/.github" -not -path "$GITHUB_WORKSPACE/.git"); do
          zip -r "${dir}.zip" "$dir" -x "FoodieFlow-lambda-tf/FoodieFlow-lambda-tf/.git/*"
          aws s3 cp "${dir}.zip" s3://lambda-foodieflow/
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
